### ISSUE TITLE
RM-Bridge-Server 無法找到設備 

### ISSUE THREAD

**Issue by ji3g4m6zo6** [KillingJacky/RM_Bridge_Server#2]
您好 謝謝您提供`RM-Bridge-Server image`
執行後發現 Server 有啟動
但無法透過`RM Bridge - Management Console(Web)`搜尋到 RM2 設備
請問您能正常運作嗎？（我的環境透過原生安卓 App 能搜尋到）
謝謝

**Comment by KillingJacky** [comment]
我也不能，不好使。我这个库是fork别人的。

**Comment by ji3g4m6zo6** [comment]
了解，謝謝你
